name: 🚀 Run All Sports Updates (Main Controller)

on:
  workflow_dispatch:
  schedule:
    - cron: "*/30 * * * *"

jobs:

  main_sm_data:
    uses: ./.github/workflows/main_sm_data.yml

  sports_data_combine:
    needs: main_sm_data
    if: ${{ always() }}
    uses: ./.github/workflows/sports_data_combine.yml

  sports_playlist:
    needs: sports_data_combine
    if: ${{ always() }}
    uses: ./.github/workflows/sports_playlist.yml
