name: Run All Sports Updates (Main Controller)

on:
  workflow_dispatch:

jobs:

  main_sm_data:
    uses: ./.github/workflows/main_sm_data.yml
    secrets: inherit

  sports_playlist:
    needs: main_sm_data
    if: ${{ always() }}
    uses: ./.github/workflows/sports_playlist.yml
    secrets: inherit
