name: Auto Generate M3U & Posters

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Dependencies
        run: pip install requests pytz Pillow

      - name: Run Script
        run: python generate.py

      - name: Commit and Push
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add Sports_data.m3u posters/
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto update Sports_data.m3u and Posters" && git push)
