name: Sports Data Auto Update

on:
  workflow_dispatch:
  schedule:
    - cron: '*/30 * * * *' # প্রতি ৩০ মিনিট পর পর স্বয়ংক্রিয়ভাবে চলার জন্য

permissions:
  contents: write

jobs:
  scrape_and_commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Public Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install cloudscraper beautifulsoup4 requests pytz Pillow

      - name: Fetch Python Script from Private Repo
        env:
          REPO_NAME: ${{ secrets.SECRET_REPO_NAME }}
        run: |
          git clone https://${{ secrets.GH_PAT }}@github.com/sm-monirulislam/$REPO_NAME.git private_code
          mkdir -p 
          cp private_code/sports_image.py
          rm -rf private_code

      - name: Run Scraper Script
        run: python sports_image.py

      - name: Clean up Python Script
        run: rm -f sports_image.py

      - name: Commit and Push M3U and Match Images
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # তৈরি হওয়া M3U প্লেলিস্ট এবং ইমেজ ফোল্ডার যোগ করা
          git add Sports_data.m3u match_image/

          if git diff --cached --quiet; then
            echo "No changes to commit."
          else
            git commit -m "⚡ Sports Data & Match Posters Auto-updated"
            git push origin HEAD
          fi
